require 'bundler'
require 'nokogiri'
require 'open-uri'
require 'selenium-webdriver'
require 'colorize'

require_relative '../lib/congress'
require_relative '../lib/header'
require_relative '../lib/header_quote'
require_relative '../lib/congress_output'
require_relative '../lib/elections_output'
require_relative '../lib/find_representatives'
require_relative '../lib/get_url'
require_relative '../lib/program_end'
require_relative '../lib/selenium_scraper'
require_relative '../lib/state_check'
require_relative '../lib/zip_check'
